djangoExam/board/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import PostList, PostDetail, PostCreate, PostEdit, create_reply, RepliesList, set_status_to_reply, NewsList, NewsDetail, pass_view



urlpatterns = [
    path('posts/', PostList.as_view(), name='posts'),
    path('posts/<int:pk>/', PostDetail.as_view(), name='post'),
    path('posts/post_create/', PostCreate.as_view(), name='post_create'),
    path('posts/post_edit/<int:pk>', PostEdit.as_view(), name='post_edit'),
    path('posts/<int:pk>/reply_create', create_reply, name='reply_create'),
    path('posts/author/replies', RepliesList.as_view(), name='replies_list'),
    path('posts/set_status_to_reply/', set_status_to_reply, name='set_status'),
    path('posts/news/', NewsList.as_view(), name='news_list'),
    path('posts/news/<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('posts/pass/', pass_view, name='pass'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoExam/djangoExam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    #path("accounts/", include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoExam/board/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from crum import get_current_user


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.id, filename)

class Post(models.Model):
    CATEGORIES = [
        ('TA', 'Танки'),
        ('HL', 'Хилы'),
        ('DD', 'ДД'),
        ('TR', 'Торговцы'),
        ('GM', 'Гилдмастеры'),
        ('QG', 'Квестгиверы'),
        ('SM', 'Кузнецы'),
        ('TN', 'Кожевники'),
        ('PT', 'Зельевары'),
        ('SP', 'Мастера заклинаний'),
    ]

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post', editable=False,
                               blank=True, null=True, default=None)
    title = models.CharField(max_length=64)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    pictures = models.ImageField(upload_to='pictures', blank=True)
    category = models.CharField(max_length=2, choices=CATEGORIES, default='TA')
    text = models.TextField()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post', args=[str(self.pk)])


class Replies(models.Model):
    STATUSES = [
        ('A', 'принят'),
        ('N', 'получен'),
        ('D', 'отменён'),
    ]

    text = models.TextField()
    status = models.CharField(max_length=1, choices=STATUSES, default='N')
    time_in = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reply', editable=False,
                             blank=True, null=True, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
            if kwargs.get('pk') and not self.post:
                pk = int(kwargs['pk'])
                self.post = Post.objects.get(pk=pk)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.text}'

    def show_date(self):
        return self.time_in.date()

class News(models.Model):
    title = models.CharField(max_length=64)
    text = models.TextField()
    pictures = models.ImageField(upload_to='pictures', blank=True)
    time_in = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news',
                               editable=False, blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if not self.pk:
            self.author = user
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.pk)])

    def show_preview(self):
        return f'{self.text[:64]}...'

    def date_in(self):
        return self.time_in.date()

djangoExam/templates/base.html
<!DOCTYPE html>
{% load static %}


<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>

        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="shortcut icon" href="{%  static 'favicon/favicon.ico' %}"/>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="/admin/">Доска Объявлений</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="pass/">Hi!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="news/">Новости</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="posts/">Объявления</a>
                        </li>
                        {% if perms.appboard.add_post %}
                        <li class="nav-item">
                            <a class="nav-link" href="post_create/">Новое объявление</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="nav-right">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_active and user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'replies_list' %}">Отклики</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profile_user' pk=user.id %}">
                                    Профиль {{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="accounts/logout">Выход</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="accounts/login">Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="accounts/signup">Регистрация</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>

djangoExam/templates/new_send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Send news {{ news_list }}</title>
</head>
<body>
    {% for new in news %}
        <h4>Новость {{ new.pk }}</h4>
        <p>***</p>
        <h3>{{ new }}</h3>
        <h5>{{ new.time_in|date:'d M Y l' }}</h5>
        <br>
        <p><em>{{ new.text }}</em></p>
        <h5><em><a href="{{ link }}{{ new.pk }}/">Для просмотра полной новости пройдите по ссылке</a></em></h5>
        <p>***</p>
        <hr><br>
    {% endfor %}
</body>
</html>

djangoExam/templates/news_detail.html
{% extends 'base.html' %}

{% block title %}
News {{ new.pk }}
{% endblock title %}

{% block content %}
    <h4>Новость {{ new.pk }}</h4>
    <hr>
    <p>&nbsp;</p>
    <h3>{{ new }}</h3>
    <h6>{{ new.time_in|date:'d M Y l' }}</h6>
    <p>&nbsp;</p>
    <p><em>{{ new.text }}</em></p>
    <p>{{ new.content|safe }}</p>
    <img src="{{ new.pictures.url }}" height="300" width="250"  />
    <p>_____</p>
{% endblock content %}

djangoExam/templates/news_list.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}
 
{% block content %}
    <h4>Новости</h4>
    <h6>показано {{ news|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if news %}
        <center><table>
            <tr>
                <td>Новость</td>
                <td>&emsp;</td>
                <td>Превью</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
            </tr>
            {% for new in news %}
            <tr>
                <td><a href="{{ new.id }}">{{ new.title|upper }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ new.id }}">{{ new.preview }}</a></td>
                <td>&emsp;</td>
                <td>{{ new.time_in|date:'M d Y' }}</td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Отсутствие новостей - хорошая новость!</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}

djangoExam/templates/pass.html
{% extends "base.html" %}

{% block title %}
Hi!
{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        <p>&nbsp;</p>
        <h4>{{ user.username }}, вы авторизованы!</h4>
        <hr>
        <p>&nbsp;</p>
        <a href="{% url 'profile_user' pk=user.id %}">Ваш профиль</a>
    {% else %}
        <p></p>
        <h4>Не залогинен</h4>
        <hr>
    {% endif %}
{% endblock content %}

djangoExam/templates/post.html
{% extends 'base.html' %}

{% block title %}
Post {{ post.pk }}
{% endblock title %}

{% block content %}
    <h3>{{ post.author }}</h3>
    <h4>Объявление {{ post.pk }}</h4>
    <hr>
    <p>&nbsp;</p>
    <h4>{{ post.get_category_display }}</h4>
    <h3>{{ post }}</h3>
    <h6>{{ post.time_in|date:'d M Y l' }}</h6>
    <p>&nbsp;</p>
    <p>{{ post.text }}</p>
    {% if post.pictures %}
    <img src="{{ post.pictures.url }}" height="300" width="250" />
    {% endif %}
    {% if perms.appboard.change_post and user == post.author %}
        <p>_____</p>
        <a href="">
        <input type="submit" class="mt-3 btn-primary" value="Редактировать" /></a>
    {% elif user.is_authenticated %}
        <hr>
        <p>&nbsp;</p>
        <form action="{% url 'reply_create' pk=post.pk %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="hidden" name="pk" id="pk" value="{{ post.pk }}">
            <p><label for="reply_text">Написать отклик:</label></p>
            <p><input type="text" name="text" maxlength="128" required="" id="reply_text" size="128"></p>
            <p><input type="submit" class="mt-3 btn-primary" value="Сохранить" /></p>
        </form>
        <p>_____</p>

        {% if replies %}
            <h4>Ваши отклики на это объявление</h4>
            <br>
            <center><table>
                <tr>
                    <td>Отклик</td>
                    <td>&emsp;</td>
                    <td>Статус</td>
                    <td>&emsp;</td>
                    <td>Написан</td>
                </tr>
                {% for reply in replies %}
                <tr>
                    <td>{{ reply.text }}</td>
                    <td>&emsp;</td>
                    <td>{{ reply.get_status_display }}</a></td>
                    <td>&emsp;</td>
                    <td>{{ reply.time_in }}</td>
                </tr>
                {% endfor %}
            </table></center>
        {% endif %}
    {% endif %}
{% endblock content %}

djangoExam/templates/post_create.html
{% extends 'base.html' %}

{% block title %}
Post edit {{ post.pk }}
{% endblock title %}
 
{% block content %}
    {% if post.pk %}
        <h4>Редактирование объявления {{ post.pk }}</h4>
    {% else %}
        <h4>Новое объявление</h4>
    {% endif %}
    <hr>
    <p>&nbsp;</p>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
    <button type="submit">Upload</button>
    </form>{% if post_obj %}  <h3>Succesfully uploaded : {{post_obj.title}}</h3>
     <img src="{{ post.pictures.url}}" alt="connect" style="max-height:300px">
        {% endif %}
    <!--<form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="mt-3 btn-primary" value="Сохранить" />
    </form> -->
    <p>_____</p>
{% endblock content %}

djangoExam/templates/posts.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h4>Объявления</h4>
    <h6>показано {{ posts|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if posts %}
        <center><table>
            <tr>
                <td>Объявление</td>
                <td>&emsp;</td>
                <td>Категория</td>
                <td>&emsp;</td>
                <td>Автор</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
            </tr>
            {% for post in posts %}
            <tr>
                <td><a href="{{ post.pk }}">{{ post.title }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ post.pk }}">{{ post.get_category_display }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ post.pk }}">{{ post.author }}</a></td>
                <td>&emsp;</td>
                <td>{{ post.created_date }}</td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Отсутствие объявлений - это вообще не новость!</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}

djangoExam/templates/replies_list.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}
Replies to author
{% endblock title %}
 
{% block content %}
    <h4>Отклики на мои объявления</h4>
    <h6>показано {{ replies|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if replies %}
        <center><table>
            <tr>
                <td>Объявление</td>
                <td>&emsp;</td>
                <td>Категория</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
                <td>&emsp;</td>
                <td>Отклик</td>
                <td>&emsp;</td>
                <td>Статус</td>
                <td>&emsp;</td>
                <td>Автор</td>
                <td>&emsp;</td>
                <td>Отправлен</td>
                <td>&emsp;</td>
                <td>Действие</td>
            {% for reply in replies %}
            <tr>
                <td valign="bottom"><a href="posts/{{ reply.post.id }}">{{ reply.post }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom"><a href="posts/{{ reply.post.id }}">{{ reply.post.get_category_display }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom"><a href="posts/{{ reply.post.id }}">{{ reply.post.time_in|date:'M d Y' }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.get_status_display }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.author }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.time_in|date:'M d Y' }}</td>
                <td>&emsp;</td>
                <td valign="top">
                {% if reply.status == 'C' %}
                    <form action="{% url 'set_status_to_reply' %}?next={{ request.get_full_path }}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="pk" id="pk" value={{ reply.pk }}>
                        <input type="submit" class="mt-3 btn-primary" name="accept" value="Принять" />
                        <input type="submit" class="mt-3 btn-primary" name="reject" value="Отклонить" />
                    </form>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Нет откликов</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}